### ISSUE TITLE
Update the ONIX CLI to accept user input

### ISSUE THREAD

**Issue by vishi24** [beckn/beckn-utilities#11]
## Description
The current CLI for the ONIX installer is designed to work with only the default configurations, this has to be updated to take input from the user and update the same at the runtime.

## Goals

- [ ] Update the ONIX installer CLI to accept and process user input as configurations.
- [ ] Updating default configuration in ONIX with user-provided information.

## Expected Outcome
When ONIX CLI is executed, the user should be prompted for the input values and the same should be applied to the services.

## Acceptance Criteria

- [ ] On executing the CLI, the user should be prompted for input and the containers should be up and running using the user-provided values.

## Implementation Details

NA

## Mockups / Wireframes

NA

---

[Please note that the below section of the ticket ****has to be in the format as mentioned as it is key to enabling proper listing of the project.**** Please only choose the options mentioned under the headings wherever applicable.]

### Product Name

ONIX

### Project Name

ONIX

### Organization Name:

FIDE

### Domain

NA

### Tech Skills Needed:

Docker
Docker-compose
Shell

### Complexity

High

### Category

Deployment

### Sub Category

CLI

**Comment by prasad-takale-eminds** [comment]
Users can input the below details from BAP and BPP. 
Subscriber ID
Subscriber URL
Registry URL with option with default: https://registry.becknprotocol.io/subscribers
Webhook URL (For BPP)

**Comment by vishi24** [comment]
The script has been tested to accept user input and found to be working as expected, hence closing the ticket.
