### ISSUE TITLE
Optimise AWS cost to USD 2500 monthly billing

### ISSUE THREAD

**Issue by faizmagic** [beckn/beckn-utilities#111]

**Comment by viraj89** [comment]
Similar ticket is updated and has been tracked here - https://github.com/beckn/beckn-ui-workspace/issues/1663 
Hence marking this as closed.

**Comment by faizmagic** [comment]
@prasad-takale-eminds , please update the following details 
1. count of running instances
2. August AWS billing projection.
3. Regarding the MIT instances, have we shutdown both India and US instances, based on my knowledge there are 28 MIT instances created (14 per region)

CC: @viraj89 @vbabuEM @emmayank

**Comment by prasad-takale-eminds** [comment]
@faizmagic We have started some of the MIT EC2 instances for catalog migration. 
Ticket for the same. [#1733](https://github.com/beckn/beckn-ui-workspace/issues/1733)

Please find below the screenshot for the forecasted cost for August the cost will be around **$5,308.53**. 
 


![Image](https://github.com/user-attachments/assets/9e180096-9881-4e92-966a-98442505b6ac)

Note: I am still working to see if we can reduce this cost further without impacting existing services.

**Comment by prasad-takale-eminds** [comment]
Deleted the CloudWatch Logs and change the retention policy from 'Never Expire' to 'Month'. Which will reduce some cost on AWS Cloud Watch.

**Comment by prasad-takale-eminds** [comment]
We have deleted some old AMI wich will reduce the cost in EC2-others.

**Comment by prasad-takale-eminds** [comment]
@faizmagic Can you please check the EC2 instances as well if we are good to shut them down?

App URL: 
https://retailreferencebap.becknprotocol.io
https://api.retailreferencebap.becknprotocol.io/
https://market.becknprotocol.io/


For the below URL's working with the team. 

https://retail-bpp-infra1.becknprotocol.io/dashboard
https://retail-bpp-infra2.becknprotocol.io/dashboard
https://tourism-bpp-infra1.becknprotocol.io/
https://taxibpp-demo.becknprotocol.io/

bpp-ps-client-pf.becknprotocol.io
bpp-ps-network-pf.becknprotocol.io
bpp-ps-client-pf-staging.becknprotocol.io
bpp-ps-network-pf-staging.becknprotocol.io

**Comment by viraj89** [comment]
@prasad-takale-eminds - Any final updates on this? as we discussed earlier today, can you please share post the latest forecast amount? That will be our baseline number to keep track.

**Comment by prasad-takale-eminds** [comment]
After stopping all possible EC2 instances and deleting old AMI we have reduced 54% compared to last month for the same period. The total forecasted cost for the current month is $5,609.28 which is 53% compared to last month's total costs. 


![Image](https://github.com/user-attachments/assets/45db60f2-92da-467a-b04b-27b15f0fe6fb)

@viraj89 @faizmagic 
**To reduce costs further, we'll need to consider reserving the EC2 instances.**
