### ISSUE TITLE
Implement Weather-Related Use Case on Vistaar

### ISSUE THREAD

**Issue by emmayank** [beckn/beckn-utilities#118]
### Description:
Create and implement the first-cut version of a weather-related use case on the Vistaar platform. This use case will involve specifying **tag groups and tags** relevant to various weather parameters, such as weather conditions, temperature, wind speed, precipitation intensity, and humidity levels. The task also includes updating the Tekdi reference application to reflect these changes.

###  Goals
To define and integrate weather-related tags and tag groups within the Vistaar platform for the initial demo. The setup will serve as a foundational version, to be refined later based on feedback and further analysis.

### Expected Outcome:
1. Defined tag groups and tags for weather-related use case on the Vistaar platform. 
2. Example JSONs demonstrating how the tags can be used in practice.
3. Work with the tekdi team (amol, suraj, vinod) to update the Tekdi reference application to support the newly defined weather tags and tag groups.

### Acceptance Criteria:
- [ ] The specified tag groups and tags are correctly implemented and can be accessed in the Vistaar platform.
- [ ] Example JSONs are provided and correctly represent the use case scenarios.
- [ ] The Tekdi reference application is updated and reflects the new weather-related tags and tag groups.
- [ ] The internal demo success

### References
1. Refer to the Climate resilience JSONs created before.

### Product Name:
Vistaar

### Domain:
Climate

### Tech Skills Needed:
Specification

### Complexity:
High

### Category:
Design & Documentation

### Sub Category:
Specification

**Comment by emmayank** [comment]
Hey @rajaneeshk90 , please reach out to @bharath-ganapathy  for further information

**Comment by rajaneeshk90** [comment]
Had calls with the Vinod, Ashwin, Amond, Suraj from Tekdi.

MOM:
- Got the context and the expectation.
- Deadline is set for Monday 19th. 
- Currently it will have search and on_search
- to go through the attached doc to come up with relevant tags.
- to have a look at other weather sites to see what they are sending additionally.


[IMD API List.pdf](https://github.com/user-attachments/files/16655031/IMD.API.List.pdf)

**Comment by rajaneeshk90** [comment]
A consolidated file created based on the initial look into the shared pdf.

https://docs.google.com/spreadsheets/d/1YwYYwPKl52I2ejBTlz5eP88u29nbj5QEm20bJuiguCw/edit?gid=0#gid=0
