### ISSUE TITLE
Automation Approach for Sanbox 2.0 documentation & discussion #1

### ISSUE THREAD

**Issue by emmayank** [beckn/beckn-utilities#120]
### Description
Develop a comprehensive automation (mocking) approach for Sandbox 2.0 utilizing Strapi. The primary focus is on mocking on_status updates. This task involves creating a detailed approach document and identifying all domains supported by Strapi.

### Goals
- [ ] Document the automation strategy for mocking on_status updates and any other if required
- [x] Identify all domains supported by Strapi that are relevant to this project.
- [x] Create a detailed approach document to guide the implementation.
- [x] Ensure the approach is scalable, maintainable, and aligned with project goals.

### Expected Outcome
1. A well-documented automation approach that can be used by the team to implement the necessary mocking.
2. A list of all domains supported by Strapi and how they will be utilized in the automation.
3. Clear guidelines on how to implement the mocking for on_status updates and other api calls in Sandbox 2.0.

### Acceptance Criteria
- [x] Comprehensive approach document created and reviewed.
- [x] All relevant domains supported by Strapi are identified and documented.
- [x] Mocking of on_status updates is defined with clear steps for implementation.

### Product Name
Sandbox 2.0

### Domain
Sandbox 

### Tech Skills Needed
- Backend Development

### Complexity
Medium

### Category
Sandbox

### Sub Category
Feature Implementation

**Comment by shreyvishal** [comment]
Current Status: We have done some discussion and brain storming and have documented the approach in the confluence sheet
[Link](https://fide-official.atlassian.net/wiki/spaces/EC/pages/edit-v2/553615361?draftShareId=bb2421d6-77dc-4655-aa03-ff70c1f2aa88)
