### ISSUE TITLE
Create catalogue for non supported domains in strapi

### ISSUE THREAD

**Issue by emmayank** [beckn/beckn-utilities#121]
### Description
Identify and create catalogues for domains that are not natively supported by Strapi. This involves uploading all identified catalogues to the system and making necessary changes in the schema to ensure compatibility and functionality.

### Goals
- [ ] Identify domains that are not supported by Strapi.
- [ ] Create catalogues for these non-supported domains.
- [ ] Upload the created catalogues into Strapi.
- [ ] Modify the schema as required to accommodate these new catalogues.

### Expected Outcome
1. A complete set of catalogues for all non-supported domains is created and uploaded into Strapi.
2. The schema is updated and functional to support these new domains.

### Acceptance Criteria
- [ ] All non-supported domains are identified and catalogued.
- [ ] Catalogues are successfully uploaded into Strapi.
- [ ] Schema changes are implemented and tested to ensure proper integration.

### Product Name
Sandbox 2.0

### Domain
Sandbox 

### Tech Skills Needed
- Backend Development

### Complexity
Medium

### Category
Sandbox

### Sub Category
Feature Implementation

**Comment by em-abee** [comment]
Not required as individual tickets are already created and assigned to @shreyvishal

**Comment by emmayank** [comment]
Review Completed - No hours being logged for this ticket.
