### ISSUE TITLE
Create DB Dump for MIT instances, Dev, BOC for backup

### ISSUE THREAD

**Issue by emmayank** [beckn/beckn-utilities#122]
### Description
Create a complete database dump for the MIT, Dev, and BOC environments to serve as a backup. This ensures that if anything goes unplanned during the deployment or testing phases, a failover plan is in place to restore the environments quickly and effectively.

### Goals
1. Create a database dump for each of the MIT, Dev, and BOC environments.
2. Store these backups securely to ensure they are available if a rollback or recovery is needed.
3. Document the backup process and the location of the stored dumps.

### Expected Outcome
1. A full database dump is created for the MIT, Dev, and BOC environments.
2. The dumps are securely stored in a location that is easily accessible in case of emergency.
3. The backup process is documented, and the team is informed about the location and usage of these backups.

### Acceptance Criteria
- [ ] Database dumps are successfully created for MIT, Dev, and BOC environments.
- [ ] The dumps are verified to ensure they are complete and functional.
- [ ] The dumps are securely stored and accessible in case of failure.

### Product Name
Sandbox 2.0

### Domain
Sandbox 

### Tech Skills Needed
- Database

### Complexity
Medium

### Category
Sandbox

### Sub Category
Feature Implementation

**Comment by shreyvishal** [comment]
Current Status: Have created DB dumps for all the env mentioned above and have used the DB dump of dev env to be deployed in BOC strapi sandbox 2.0
