### ISSUE TITLE
Deploy Latest Strapi and Plugins codebase to BOC Sandbox 2.0

### ISSUE THREAD

**Issue by emmayank** [beckn/beckn-utilities#124]
### Description
Deploy the latest version of the Strapi platform and its associated plugins to the BOC Sandbox 2.0 environment. This deployment will ensure that the environment is up-to-date with the most recent features & changes.

### Goals
- [x] Update the BOC Sandbox 2.0 environment with the latest Strapi and plugins codebase.
- [x] Ensure that the deployment is smooth, with no disruption to existing functionalities.
- [x] Validate the deployment to confirm that all new features and fixes are working as expected.

### Expected Outcome
1. The BOC Sandbox 2.0 environment is successfully updated with the latest Strapi and plugins codebase.
2. All existing and new functionalities are working correctly after the deployment.
3. Any issues encountered during the deployment are documented and addressed.

### Acceptance Criteria
- [x] The latest Strapi codebase and plugins are deployed to the BOC Sandbox 2.0 environment.
- [ ] The environment is tested to ensure that all functionalities are operational post-deployment.
- [x] Any issues or bugs identified during or after deployment are resolved.
- [x] The deployment process is documented, including any challenges and how they were overcome.

### Product Name
Sandbox 2.0

### Domain
Sandbox 

### Tech Skills Needed
- Strapi

### Complexity
Medium

### Category
Sandbox

### Sub Category
Feature Implementation

**Comment by emmayank** [comment]
tes the env first in dev and then in boc

**Comment by shreyvishal** [comment]
Current Status: Have deployed in the BOC env and the url is [BOC Strapi](https://boc-unified-strapi-sandbox.becknprotocol.io)
![Image](https://github.com/user-attachments/assets/250794f9-7464-45c8-b880-8b4642f59bbb)

**Comment by emmayank** [comment]
Review Completed
