### ISSUE TITLE
Migrate DB from Dev Strapi to BOC

### ISSUE THREAD

**Issue by emmayank** [beckn/beckn-utilities#125]
### Description
Migrate the database from the Dev Strapi environment to the BOC environment. This task ensures that the BOC environment is synchronized with the latest data and configurations from the Dev environment, providing a consistent testing and development experience.

### Goals
- [ ] Successfully migrate the Dev Strapi database to the BOC environment.
- [ ] Ensure that all data, configurations, and content types are correctly transferred.
- [ ] Validate the BOC environment post-migration to ensure that everything is functioning as expected.

### Expected Outcome
1. The BOC environment is fully synchronized with the Dev Strapi database.
2. All data and configurations are intact and functional in the BOC environment.
3. The BOC environment is tested and confirmed to be working correctly post-migration.

### Acceptance Criteria
- [ ] The database from the Dev Strapi environment is successfully migrated to the BOC environment.
- [ ]  No data loss or corruption occurs during the migration process.
- [ ]  The BOC environment is thoroughly tested to ensure all functionalities are operational.
- [ ]  Any issues or discrepancies identified during the migration are resolved.

### Product Name
Sandbox 2.0

### Domain
Sandbox 

### Tech Skills Needed
- Database

### Complexity
Medium

### Category
Sandbox

### Sub Category
Feature Implementation

**Comment by prasad-takale-eminds** [comment]
@emmayank What is the next plan of action on this task?

**Comment by prasad-takale-eminds** [comment]
The development team has successfully completed this activity, and no further DevOps efforts are needed. Closing this issue.
