### ISSUE TITLE
Reference Application: Sandbox 2.0

### ISSUE THREAD

**Issue by emmayank** [beckn/beckn-utilities#126]
## Description
Based on the documented automation approach for Sandbox 2.0, create a separate branch in the repository to implement the required code changes. These changes will focus on mocking `on_status` updates and any necessary adjustments to the schema as per the identified approach.

## Goals
- [x] Create a new branch for Sandbox 2.0 in the repository.
- [x] Implement the code changes based on the documented automation approach.
- [x] Ensure that the changes are isolated to this branch for proper testing and review.
- [ ] **<To be updated after finalization of the approach>**

## Expected Outcome
- A separate branch with all the required code changes for Sandbox 2.0.
- The implementation is aligned with the documented approach for mocking `on_status` updates.

## Acceptance Criteria
- [x] A new branch named `sandbox-2.0-automation` (or a suitable name) is created.
- [x] All code changes are made according to the documented approach.
- [x] The branch passes initial tests and is ready for review.

## Mockups / Wireframes
NA

## Product Name
Sandbox 2.0

## Domain
Sandbox

## Tech Skills Needed
- Backend Development
- API Integration
- Schema Adjustments

## Complexity
Medium

## Category
Feature Implementation

## Sub Category
Automation

**Comment by shreyvishal** [comment]
Current Status: Since we are using the Gen AI catalogue generation and is being used in BOC Env. And there are lots of Domain used in that ENV, so this change is not required as of now.

**Comment by emmayank** [comment]
Current status ( 17th Dec, 24)
1. All domains are included in sandbox 2.0 , except 2

Next Step
1. Documentation
2. QA signoff
3. Release

**Comment by emmayank** [comment]
**Current status ( 19th Dec, 24)**
1. Documentation - In progress
2. QA - In progress

**Next Step**
1. QA signoff
2. Release

**Comment by emmayank** [comment]
**Current status ( 19th Dec, 24)**
1. User Guide Documentation - Done, Available [here](https://github.com/beckn/beckn-sandbox/blob/main/artefacts/sandbox%202.0/README.md)
2. QA - Signoff - Done
3. Postman collection & documentation available here - https://github.com/beckn/beckn-sandbox/tree/main/artefacts/sandbox%202.0

**Next Step**
1. Bug Fixing & QA
