### ISSUE TITLE
Deploy the changes to BOC env only with the created branch

### ISSUE THREAD

**Issue by emmayank** [beckn/beckn-utilities#127]
### Description
Deploy the code changes from the `sandbox-2.0-automation` branch (or the branch created for Sandbox 2.0) to the BOC environment. This will allow for isolated testing and validation of the changes in a controlled environment before merging them into the main branch.

### Goals
- [ ] Deploy the changes from the sandbox-2.0-automation branch to the BOC environment.
- [ ] Ensure that the deployment is successful and that the environment is stable.
- [ ] Test the functionality related to on_status updates and any schema changes in the BOC environment.

### Expected Outcome
1. The changes from the sandbox-2.0-automation branch are successfully deployed to the BOC environment.
2. The BOC environment reflects the new functionality for on_status updates and any other changes made.
3. All deployed features are tested and validated in the BOC environment.

### Acceptance Criteria
- [ ]  Deployment to the BOC environment is successful with no major issues.
- [ ]  All functionalities, including on_status updates, work as expected in the BOC environment.
- [ ]  Any issues or bugs identified during testing are documented and addressed.
- [ ]  The deployment is reviewed and signed off by relevant stakeholders.

### Product Name
Sandbox 2.0

### Domain
Sandbox 

### Tech Skills Needed
- Devops

### Complexity
Medium

### Category
Sandbox

### Sub Category
Feature Implementation

**Comment by prasad-takale-eminds** [comment]
@emmayank What is the next plan of action on this task?

**Comment by prasad-takale-eminds** [comment]
The development team has successfully completed this activity, and no further DevOps efforts are needed. Closing this issue.
