### ISSUE TITLE
ONIX user guide

### ISSUE THREAD

**Issue by faizmagic** [beckn/beckn-utilities#13]
## Description
Prepare a user guide on how to use the ONIX installer. This will be a living document, based on the updates and features which will be added to ONIX

## Goals

- [ ] Create a readme.md file in the root folder of the beckn-utilities repo
- [ ] List down the all the ONIX uitility in the readme file and  provide a small description of what ONIX is and attach a link to the ONIX user guide
- [ ] Create a ONIX user guide inside the ONIX-Installer foledr

## Expected Outcome
User should be able to access and navigate to the the ONIX user guide from the beckn-utilities readme file

## Acceptance Criteria

- [ ] User should be able to access and navigate to the the ONIX user guide from the beckn-utilities readme file

## Implementation Details

NA

## Mockups / Wireframes

NA

---

[Please note that the below section of the ticket ****has to be in the format as mentioned as it is key to enabling proper listing of the project.**** Please only choose the options mentioned under the headings wherever applicable.]

### Product Name

ONIX

### Project Name

ONIX

### Organization Name:

FIDE

### Domain

NA

### Tech Skills Needed:

Documentation 

### Complexity

Low

### Category

Documentation

### Sub Category

User guide

**Comment by faizmagic** [comment]
@prasad-takale-eminds, if this issues is completed, please move the ticket to review state and request @vishi24 and @vbabuEM to review the documentation.

@vishi24 , please ensure the ticket status are updated on a daily bais.

**Comment by prasad-takale-eminds** [comment]
README file is created for onix deployment. 
Link: https://github.com/beckn/beckn-utilities/blob/main/onix-installer/START_BECKN.md
Also same URL is updated in the main README.md file
