### ISSUE TITLE
create a new subdomain under the becknprotocol.io DNS to Specified IP Address

### ISSUE THREAD

**Issue by emmayank** [beckn/beckn-utilities#133]
## Description
We need to create a new subdomain under the becknprotocol.io DNS and point it to a specified IP address. The subdomain `blog` should be set up as an A Record with the following details:

- **Type**: A
- **Name**: blog
- **Value**: 52.66.179.176

Once the A Record has been updated, an email confirmation should be sent to Sonam, with Ravi, Faiz, and Mayank cc'd.

## Goals
- [ ] Create the `blog` subdomain under becknprotocol.io.
- [ ] Point the `blog` subdomain to the IP address 52.66.179.176.
- [ ] Send email confirmation to Sonam and cc Ravi, Faiz, and Mayank.

## Expected Outcome
- [ ] The `blog` subdomain is successfully created and pointed to the specified IP address.
- [ ] Email confirmation is sent to the specified contacts.

## Acceptance Criteria
- [ ] The A Record for `blog` is created and correctly points to 52.66.179.176.
- [ ] Confirmation email is sent to Sonam, with Ravi, Faiz, and Mayank cc'd.

## Mockups / Wireframes
NA

## Product Name
Beckn

## Domain
Infra

## Tech Skills Needed
DNS Management, DevOps

## Complexity
Low

## Category
Infrastructure

## Sub Category
Domain Setup

**Comment by prasad-takale-eminds** [comment]
We have created the required DNS entry. 
[blog.becknprotocol.io](url)

Below is the SS for the same. 
DNS entry 
![image](https://github.com/user-attachments/assets/0d447cb0-1c9f-458b-b925-bcc67f8fc993)

URL access

![image](https://github.com/user-attachments/assets/dc99dd6b-1fa5-41d0-980a-a3f2c66dad8a)

**Comment by emmayank** [comment]
**Review Completed** - Working fine



![Image](https://github.com/user-attachments/assets/80743e29-dab6-422b-a361-4d708a0bf9f2)

**Comment by emmayank** [comment]
@prasad-takale-eminds  please select theuncheck items if they are done, if not done, please do and send
