### ISSUE TITLE
To get the list of all static IPs

### ISSUE THREAD

**Issue by viraj89** [beckn/beckn-utilities#135]

**Comment by prasad-takale-eminds** [comment]
List of all Static IP's used by currently running EC2 instances along with the EC2 instances details and application URL's  is updated in the below spreadsheet. 
https://docs.google.com/spreadsheets/d/14rcwtUakinYpf6XfOw83RAnPM1Airnwd/edit?pli=1&gid=39528701#gid=39528701
Please check the "AWS Instances of as Aug 22, 2024" tab in the spreadsheet.

**Comment by emmayank** [comment]
**Review Completed**

details are available from the above sheet shared

![Image](https://github.com/user-attachments/assets/f89d8e9b-c25d-4a01-972d-861b18e214de)
