### ISSUE TITLE
Create CI/CD Pipeline for Policy Admin Portal (Dev, Staging, Prod)

### ISSUE THREAD

**Issue by viraj89** [beckn/beckn-utilities#140]
## Description
Develop a CI/CD pipeline for the Policy Admin Portal across the following environments:

- **Dev:** [policyadmin-dev.becknprotocol.io](https://policyadmin-dev.becknprotocol.io)
- **Staging:** [policyadmin-staging.becknprotocol.io](https://policyadmin-staging.becknprotocol.io)
- **Prod:** [policyadmin-prod.becknprotocol.io](https://policyadmin-prod.becknprotocol.io)

This Policy Admin Portal is a critical dependency for mobility-related applications on the Experience Center.

## Goals
- Set up a robust CI/CD pipeline for automated deployment and updates for all three environments.
- Ensure seamless and automated integration between the development, staging, and production environments.
- Improve deployment speed and reliability for the Policy Admin Portal.

## Expected Outcome
A fully functional and automated CI/CD pipeline for the Policy Admin Portal in the Dev, Staging, and Prod environments, ensuring efficient and reliable updates.

## Acceptance Criteria
- [x] CI/CD pipeline is created for the **Dev** environment.
- [x] CI/CD pipeline is created for the **Staging** environment.
- [x] CI/CD pipeline is created for the **Prod** environment.
- [x] Deployment processes are automated and verified for each environment.
- [x] Mobility-related apps in the Experience Center are not impacted during deployments.

## Mockups / Wireframes
NA

## Product Name
Policy Admin Portal

## Domain
DevOps

## Tech Skills Needed
- CI/CD Pipeline Setup
- Deployment Automation
- DevOps Tools (Jenkins, GitHub Actions, etc.)
- Environment Management

## Complexity
Medium

## Category
DevOps

## Sub Category
CI/CD Pipeline Creation

**Comment by em-tpt-bbandi** [comment]
cicd is created for Dev: [policyadmin-dev.becknprotocol.io](https://policyadmin-dev.becknprotocol.io/)

https://jenkins.becknprotocol.io/job/Policy-Admin/job/policyadmin-dev/

![image](https://github.com/user-attachments/assets/a3b36b38-b0d7-4b79-8bc5-cead7a77a9a5)


cicd is created for Staging: [policyadmin-staging.becknprotocol.io](https://policyadmin-staging.becknprotocol.io/)

https://jenkins.becknprotocol.io/job/Policy-Admin/job/policyadmin-staging/

![image](https://github.com/user-attachments/assets/4340afe2-750b-49e8-bb8a-39a11aa148c2)


created cicd for Prod: [policyadmin-prod.becknprotocol.io](https://policyadmin-prod.becknprotocol.io/)

https://jenkins.becknprotocol.io/job/Policy-Admin/job/policy-admin-ui-S3-prod/

![image](https://github.com/user-attachments/assets/f3e4893d-01b9-4bae-b4cf-044c33bdd9b0)

**Comment by emmayank** [comment]
Review Completed
