### ISSUE TITLE
Detailed analysis of all the AWS instances on draw.io

### ISSUE THREAD

**Issue by viraj89** [beckn/beckn-utilities#143]
#### Problem and Background:

Using an Excel sheet for tracking the AWS EC2 landscape often lacks clarity and can be difficult to interpret. To improve visibility, the current AWS EC2 infrastructure needs to be represented visually in draw.io. This will offer a more intuitive and detailed view of EC2 instances across different environments like BOC, development, staging, and production, along with other key infrastructure components.

Additionally, orphaned or independent EC2 instances are sometimes overlooked, making it hard to determine if they are still required after the work is completed. Visual representation will help mitigate this issue by ensuring all instances are accounted for and properly tracked.

The existing landscape document [here](https://fide-official.atlassian.net/wiki/spaces/EC/pages/310411266/Beckn+One+Ver+1.1+Infra+landscape+-+Development) can be utilized a reference point to begin. 

## Goals
- [x] Create separate layers for BOC, dev, staging, and production environments.
- [x] Represent all EC2 instances with key details such as instance ID, type, region, and AMI.
- [x] Show security group associations and access rules.
- [x] Visualize interconnections between environments and external systems.

## Expected Outcome
A draw.io diagram that accurately visualizes the AWS EC2 landscape for BOC, dev, staging, and production environments, making it easy to view the links and dependencies in a precise manner.

## Acceptance Criteria
- [x] The diagram includes separate layers for each environment.
- [x] All EC2 instances are labeled with their key details.
- [x] Interconnections between environments and external systems are shown clearly.

## Mockups / Wireframes
TBD

## Product Name
Beckn AWS

## Domain
Infra

## Tech Skills Needed
- AWS EC2
- Networking & Security Groups
- VPC/Subnets
- draw.io

## Complexity
Medium

## Category
Infrastructure Representation

## Sub Category
AWS EC2 Landscape

**Comment by emmayank** [comment]
**Current Progress**
1. @em-tpt-bbandi has created a draw.io file and started putting all the instance in the file. file is available over here - https://drive.google.com/file/d/1ACjwfmGDHRVTEe1wQI05rMmqJOeshqjP/view?usp=sharing
2. Done with dev, staging, prod, boc related instances

**Next Step**
1. Adding Standalone instances ( Mit, Grafana etc) and establishing relations
2. Improving the look & Feel

**Comment by em-tpt-bbandi** [comment]
Added all standalone instances.

Working with @prasad-takale-eminds for improving the look and feel

**Comment by em-tpt-bbandi** [comment]
![Image](https://github.com/user-attachments/assets/e734e988-b58d-443e-9cbc-c26878ba1ba9)

https://drive.google.com/file/d/1ACjwfmGDHRVTEe1wQI05rMmqJOeshqjP/view?usp=sharing
