### ISSUE TITLE
Retail Participants Webhook Suggested Changes and Deployment

### ISSUE THREAD

**Issue by emmayank** [beckn/beckn-utilities#144]
## Description
Implement suggested changes to the Retail Participants webhook, ensuring improved functionality and reliability. After making the changes, deploy the updated webhook to the production environment, ensuring minimal downtime and thorough testing.

## Goals
- [x] Implement suggested changes to the Retail Participants webhook.
- [x] Test the updated webhook to ensure it functions correctly.

## Expected Outcome
- The Retail Participants webhook is updated with the suggested changes, and the deployment to production is successful without issues.
- The webhook functions reliably post-deployment.

## Acceptance Criteria
- [x] All suggested changes are implemented in the webhook.

## Mockups / Wireframes
NA

## Product Name
Beckn

## Domain
TBD

## Tech Skills Needed
- Webhooks
- JavaScript/TypeScript
- API Integration
- Deployment

## Complexity
Medium

## Category
Backend Development

## Sub Category
Webhook Integration and Deployment

**Comment by rahul-eminds** [comment]
Finished all changes suggested and merged the code
PR: https://github.com/beckn/integration-webhook/pull/24
