### ISSUE TITLE
Stop EC2 Instances for AWS Cost Optimization activity

### ISSUE THREAD

**Issue by emmayank** [beckn/beckn-utilities#145]
## Description
Stop the below-mentioned EC2 instances as per the provided details. Ensure all running instances listed are stopped to conserve resources. For the instance details, refer to the following document:  
[EC2 Instance Details](https://docs.google.com/spreadsheets/d/14rcwtUakinYpf6XfOw83RAnPM1Airnwd/edit?pli=1&gid=39528701#gid=39528701).  ( all highlighted with grey or red )

## Goals
- [x] Stop all EC2 instances mentioned in the linked document highlighted with grey/red
- [x] Verify that all instances are stopped successfully.
- [x] Ensure no resources are left running unnecessarily.

## Expected Outcome
- All EC2 instances listed in the provided document are stopped as scheduled.
- No EC2 instances are left running after the process is completed.

## Acceptance Criteria
- [x] All EC2 instances listed in the provided document are stopped at 10:53 highlighted with grey/red
- [x] Verification is done to confirm that no instance remains running.

## Mockups / Wireframes
NA

## Product Name
Beckn

## Domain
TBD

## Tech Skills Needed
- AWS EC2
- Cloud Resource Management
- EC2 Instance Management

## Complexity
Low

## Category
Cloud Operations

## Sub Category
EC2 Management

**Comment by prasad-takale-eminds** [comment]
As confirmed by Mayank we have stopped the below EC2 instances. 

Instance ID | Name | Public IP | Private IP
-- | -- | -- | --
i-07a033e6d35ed583c | taxi-bpp | 65.1.147.159 | 172.31.11.156
i-0837e1adee9949392 | retailreferenceapp-FE | 15.206.127.129 | 172.31.3.30
i-0bb267eda574e20e4 | retailreferenceapp-BE | 3.110.218.68 | 172.31.12.123
i-05bb2e20fb550e06c | taxi-admin-ui | 43.204.215.11 | 172.31.7.45
i-05dabd594dbd8cc39 | staging-taxiadminui | 43.205.136.217 | 172.31.39.182
i-0324c7520df0f17a8 | xc-center-ui-eminds | 13.127.31.186 | 172.31.34.240
i-0afb697aeb02a31cd | dsep-webhook-client | 3.109.60.141 | 172.31.35.26
i-08421ea86ee9aa0e3 | venkys-bpp-new | 13.233.216.90 | 172.31.40.179
i-090eae663f40fa816 | taxi-bpp-2 | 52.66.236.71 | 172.31.8.153
i-0f2ad24644f320292 | venkys-bpp | 43.204.100.68 | 172.31.4.240
i-0c0789742856fa01e | retail-bpp-infra1 | 3.108.16.65 | 172.31.4.118
i-029c5c181e164d288 | retail-bpp-infra2 | 3.111.103.90 | 172.31.11.134
i-0bb92e6ac5dd9c8f1 | tourism-bpp-infra1 | 52.66.125.227 | 172.31.14.240
i-043247365f54bc07c | mobility-bpp-infra1 | 3.111.58.16 | 172.31.7.159
i-0021516abbc7eee65 | mobility-bpp-infra2 | 15.207.111.235 | 172.31.7.137
i-0fa9ab01cb9d8b867 | All-UI-Application | 3.108.21.4 | 172.31.37.161
i-05e6e652b15f93b61 | mulearn-team | 43.204.138.206 | 172.31.29.253
i-012a2b7c376018bb1 | OTTL-Team | 13.233.96.254 | 172.31.5.152
i-0b460c3d7046b98a0 | None | 3.110.114.14 | 172.31.12.215

**Comment by emmayank** [comment]
Review Completed

![image](https://github.com/user-attachments/assets/753f765f-003f-4c22-be26-010bd45ea17c)
Monthly budget came down to 4850$ from 5500$ after deletion of above instance. further deletion of instances is possible after migrating connecting beckn-gpt with BOC instance
