### ISSUE TITLE
Create a detailed product requirement document for OpenSpark

### ISSUE THREAD

**Issue by emmayank** [beckn/beckn-utilities#148]

**Comment by viraj89** [comment]
Updated documentation for HyperBeckn (now called Beckn-One) after brainstorming flow ideas.
1. The final version includes:
   - Introduction
   - Architectural updates
   - API specification updates
   - Implementation details for Oct 30
   - Consumer and prosumer flows
   - Flow charts
   - User journey example JSONs
2. Doc link: [Beckn-One Documentation](https://docs.google.com/document/d/1PeolyH_g6l7R-NpKSKma_e5hE1MZt4IqY67Hv4HAHvw/edit?tab=t.0#heading=h.oqsrg9i5lujz)
