### ISSUE TITLE
ONIX V 0.2 - Enhace the CLI of ONIX installer

### ISSUE THREAD

**Issue by vishi24** [beckn/beckn-utilities#16]
## Description
The current version of ONIX UI does not have any binary logos, add BECKN binary logo to the script that will come on top initially when the script is executed.

## Goals

- [ ] Display BECKN logo in ONIX installer.
- [ ] Include generic client layer in ONIX components
- [ ] ONIX installer should execute successfully on the Server instances with OS - Ubuntu 20+ LTI , Amazon Linux and Cent OS. If any dependency is not there it should install the dependencies also ex- Docker,git.
- [ ] ONIX installer should execute successfully on local system (laptop/desktop) with OS - Windows 10+ , Linux and MAC OS. If any dependency is missing it should install by itself or if not possible should check initially and stop with an error message - pre-requisite check fail.
- [ ] ONIX installer should be able to run for 

## Expected Outcome
Ver 0.2 will cover the following features

1.      All components should install in one go without asking for any input from the user.
2.      User can install specific components with default config - Gatewy+Registry , BAP , BPP , BPP with sandbox.
3.      User can install specific components with custom config - Gatewy+Registry , BAP , BPP , BPP with sandbox.

## Acceptance Criteria

- [ ] User should be able to launch ONIX with all components or as individual complements as specified in the expected   outcome 

## Implementation Details

NA

## Mockups / Wireframes

NA

---

[Please note that the below section of the ticket ****has to be in the format as mentioned as it is key to enabling proper listing of the project.**** Please only choose the options mentioned under the headings wherever applicable.]

### Product Name

ONIX

### Project Name

ONIX

### Organization Name:

FIDE

### Domain

NA

### Tech Skills Needed:

Docker
Docker-compose
shell script
ONIX understanding

### Complexity

Medium

### Category

Deployment

### Sub Category

Scripting

**Comment by vbabuEM** [comment]
One of the other comments that Ravi had was to use colors in the CLI till we have a GUI installer.

**Comment by vishi24** [comment]
The issue contains the issues to be completed in V0.2, this has been moved to miestone.
