### ISSUE TITLE
Correct the branch structure in github

### ISSUE THREAD

**Issue by vishi24** [beckn/beckn-utilities#17]
## Description
The current branching structure needs to be updated for the below repositories

1. Protocol Server
2. Strapi BAP
3. Strapi BPP
4. Generic Client Layer

## Goals

- [ ] Create Development, Staging, master, and release branches in listed repositories.

## Expected Outcome
Development, Staging, master, and release branches must be available in listed repositories.
All the branches should be in sync in hierarchal form.

Feature branch-->Development-->Staging-->Master-->Release 

## Acceptance Criteria

- [ ] Development, Staging, master, and release branches must be available in listed repositories.

## Implementation Details

NA

## Mockups / Wireframes

NA

---

[Please note that the below section of the ticket ****has to be in the format as mentioned as it is key to enabling proper listing of the project.**** Please only choose the options mentioned under the headings wherever applicable.]

### Product Name

NA

### Project Name

NA

### Organization Name:

FIDE

### Domain

NA

### Tech Skills Needed:

Github

### Complexity

Medium

### Category

Version control

### Sub Category

Github branching

**Comment by prasad-takale-eminds** [comment]
We have created the required branches for 

Protocol Server
Strapi BAP
Strapi BPP
Generic Client Layer
