### ISSUE TITLE
Strapi BAP - Development environment setup

### ISSUE THREAD

**Issue by vishi24** [beckn/beckn-utilities#21]
## Description
The strapi BAP (https://github.com/beckn/beckn-bap-user-strapi) , currently does not have a development environment, it will be used by the development team to host in development code and test.

## Goals

- [ ] Create a Development environment for the Strapi BAP.

## Expected Outcome
Development environment setup with the minimum resources so that it can be used by the development team to test any development that is in progress.

## Acceptance Criteria

- [ ] The development environment is up and running for Strapi BAP.

## Implementation Details

NA

## Mockups / Wireframes

NA

---

[Please note that the below section of the ticket ****has to be in the format as mentioned as it is key to enabling proper listing of the project.**** Please only choose the options mentioned under the headings wherever applicable.]

### Product Name

NA

### Project Name

NA

### Organization Name:

FIDE

### Domain

NA

### Tech Skills Needed:

Git
AWS

### Complexity

Medium

### Category

Deployment

### Sub Category

Deployment

**Comment by prasad-takale-eminds** [comment]
We have created the Strapi development env. 
URL: https://strapi-bap-dev.becknprotocol.io/

**Comment by vishi24** [comment]
@prasad-takale-eminds
Is the deployment tested ?
Data migration from current strapi instance done ?
Please attach screen shot.

Please create user for Faiz and me with admin rights and share credentials over email.
