### ISSUE TITLE
Verfiable Credential Integration - integrate Dhiway API in BPP for certificate issueing & verfication

### ISSUE THREAD

**Issue by emmayank** [beckn/beckn-utilities#214]

**Comment by ankitShogun** [comment]
Related to ticket 213 and 222. Providing the summary of all utility functions created for these tickets


# HTTP Utilities Documentation

This document provides an overview of the utility functions for handling HTTP requests related to credentials, schemas, and registry operations.

## Credential Management Functions

### generateCredential
- **Purpose**: Generates new credentials using the issuer agent
- **Parameters**: 
  - `schemaId`: Schema ID for the credential
  - `properties`: Credential properties (name, email, etc.)
  - `headers`: Optional custom headers
- **Returns**: Credential response data
- **Endpoint**: `POST /api/v1/cred`

### fetchCredential
- **Purpose**: Retrieves an existing credential by its ID
- **Parameters**: 
  - `credentialId`: ID of the credential to fetch
  - `headers`: Optional custom headers
- **Returns**: Credential data
- **Endpoint**: `GET /api/v1/cred/{credentialId}`

### verifyCredential
- **Purpose**: Verifies the authenticity of a credential
- **Parameters**: 
  - `credential`: The VerifiableCredential object to verify
  - `headers`: Optional custom headers
- **Returns**: Verification response data
- **Endpoint**: `POST /api/v1/verify/credentials/verify`

## Schema Management Functions

### createSchema
- **Purpose**: Creates a new schema definition
- **Parameters**: 
  - `title`: Schema title
  - `description`: Schema description
  - `properties`: Schema properties definition
  - `headers`: Optional custom headers
- **Returns**: Schema creation response data
- **Endpoint**: `POST /api/v1/schema`

### fetchSchema
- **Purpose**: Retrieves an existing schema by its ID
- **Parameters**: 
  - `schemaId`: ID of the schema to fetch
  - `headers`: Optional custom headers
- **Returns**: Schema data
- **Endpoint**: `GET /api/v1/schema/{schemaId}`

## Registry Management Functions

### addRegistryRecord
- **Purpose**: Adds a new record to the decentralized registry
- **Parameters**: 
  - `recordData`: Object containing record details (name, description, utility company details)
  - `headers`: Optional custom headers
- **Returns**: Response data from adding the record
- **Endpoint**: `POST /dedi/{namespace}/{registryId}/addRecord`

### getRegistryRecords
- **Purpose**: Queries the registry for utility company records
- **Parameters**: 
  - `headers`: Optional custom headers
- **Returns**: Registry query response data, with records converted to array format
- **Endpoint**: `GET /dedi/query/{namespace}/{registryId}`

## Common Features
- All functions include error handling with descriptive error messages
- TypeScript generics support for flexible response types
- Consistent header handling with Content-Type defaults
- Axios-based HTTP requests
- Support for custom headers in all operations
