### ISSUE TITLE
Adding Utility company in decentralized directory

### ISSUE THREAD

**Issue by emmayank** [beckn/beckn-utilities#222]

**Comment by ankitShogun** [comment]
Related to ticket 214 and 213. Providing the summary of all utility functions created for these tickets


# HTTP Utilities Documentation

This document provides an overview of the utility functions for handling HTTP requests related to credentials, schemas, and registry operations.

## Credential Management Functions

### generateCredential
- **Purpose**: Generates new credentials using the issuer agent
- **Parameters**: 
  - `schemaId`: Schema ID for the credential
  - `properties`: Credential properties (name, email, etc.)
  - `headers`: Optional custom headers
- **Returns**: Credential response data
- **Endpoint**: `POST /api/v1/cred`

### fetchCredential
- **Purpose**: Retrieves an existing credential by its ID
- **Parameters**: 
  - `credentialId`: ID of the credential to fetch
  - `headers`: Optional custom headers
- **Returns**: Credential data
- **Endpoint**: `GET /api/v1/cred/{credentialId}`

### verifyCredential
- **Purpose**: Verifies the authenticity of a credential
- **Parameters**: 
  - `credential`: The VerifiableCredential object to verify
  - `headers`: Optional custom headers
- **Returns**: Verification response data
- **Endpoint**: `POST /api/v1/verify/credentials/verify`

## Schema Management Functions

### createSchema
- **Purpose**: Creates a new schema definition
- **Parameters**: 
  - `title`: Schema title
  - `description`: Schema description
  - `properties`: Schema properties definition
  - `headers`: Optional custom headers
- **Returns**: Schema creation response data
- **Endpoint**: `POST /api/v1/schema`

### fetchSchema
- **Purpose**: Retrieves an existing schema by its ID
- **Parameters**: 
  - `schemaId`: ID of the schema to fetch
  - `headers`: Optional custom headers
- **Returns**: Schema data
- **Endpoint**: `GET /api/v1/schema/{schemaId}`

## Registry Management Functions

### addRegistryRecord
- **Purpose**: Adds a new record to the decentralized registry
- **Parameters**: 
  - `recordData`: Object containing record details (name, description, utility company details)
  - `headers`: Optional custom headers
- **Returns**: Response data from adding the record
- **Endpoint**: `POST /dedi/{namespace}/{registryId}/addRecord`

### getRegistryRecords
- **Purpose**: Queries the registry for utility company records
- **Parameters**: 
  - `headers`: Optional custom headers
- **Returns**: Registry query response data, with records converted to array format
- **Endpoint**: `GET /dedi/query/{namespace}/{registryId}`

## Common Features
- All functions include error handling with descriptive error messages
- TypeScript generics support for flexible response types
- Consistent header handling with Content-Type defaults
- Axios-based HTTP requests
- Support for custom headers in all operations

**Comment by ankitShogun** [comment]
Below utility companies were created as a result using the dedi API


[
  {
    "authorization": "registryauth:cord:X8JY6GM9eY9qbsXmT27ARZXhf2Hkj31UjLjStf4AFVWNsvNhn",
    "recordName": "Utility company 1 - ELC001",
    "description": "Utility company data",
    "details": {
      "company_id": "ELC001",
      "company_name": "Maharashtra State Power Corp. Ltd",
      "state_region": "Maharashtra",
      "headquarters": "Mumbai",
      "contact_email": "support@mahapower.com",
      "contact_phone": "022-12345678",
      "customer_service_portal_url": "https://www.mahapower.com",
      "status": "Active",
      "der_participation": "Yes",
      "established_year": 1960
    },
    "version_count": "1.0.0"
  },
  {
    "authorization": "registryauth:cord:X8JY6GM9eY9qbsXmT27ARZXhf2Hkj31UjLjStf4AFVWNsvNhn",
    "recordName": "Utility company 1 - ELC002",
    "description": "Utility company data",
    "details": {
      "company_id": "ELC002",
      "company_name": "Gujarat Electricity Corp. Ltd",
      "state_region": "Gujarat",
      "headquarters": "Gandhinagar",
      "contact_email": "info@gujelectricity.com",
      "contact_phone": "079-87654321",
      "customer_service_portal_url": "https://www.gujelectricity.com",
      "status": "Active",
      "der_participation": "Yes",
      "established_year": 1970
    },
    "version_count": "1.0.0"
  },
  {
    "authorization": "registryauth:cord:X8JY6GM9eY9qbsXmT27ARZXhf2Hkj31UjLjStf4AFVWNsvNhn",
    "recordName": "Utility company 1 - ELC003",
    "description": "Utility company data",
    "details": {
      "company_id": "ELC003",
      "company_name": "West Bengal State Power Authority",
      "state_region": "West Bengal",
      "headquarters": "Kolkata",
      "contact_email": "contact@wbspower.com",
      "contact_phone": "033-23456789",
      "customer_service_portal_url": "https://www.wbspower.com",
      "status": "Active",
      "der_participation": "No",
      "established_year": 1955
    },
    "version_count": "1.0.0"
  },
  {
    "authorization": "registryauth:cord:X8JY6GM9eY9qbsXmT27ARZXhf2Hkj31UjLjStf4AFVWNsvNhn",
    "recordName": "Utility company 1 - ELC004",
    "description": "Utility company data",
    "details": {
      "company_id": "ELC004",
      "company_name": "Tamil Nadu Electricity Board",
      "state_region": "Tamil Nadu",
      "headquarters": "Chennai",
      "contact_email": "service@tneb.in",
      "contact_phone": "044-98765432",
      "customer_service_portal_url": "https://www.tneb.in",
      "status": "Active",
      "der_participation": "Yes",
      "established_year": 1965
    },
    "version_count": "1.0.0"
  },
  {
    "authorization": "registryauth:cord:X8JY6GM9eY9qbsXmT27ARZXhf2Hkj31UjLjStf4AFVWNsvNhn",
    "recordName": "Utility company 1 - ELC005",
    "description": "Utility company data",
    "details": {
      "company_id": "ELC005",
      "company_name": "Delhi Power Distribution Company",
      "state_region": "Delhi NCR",
      "headquarters": "New Delhi",
      "contact_email": "support@delhipower.in",
      "contact_phone": "011-65432109",
      "customer_service_portal_url": "https://www.delhipower.in",
      "status": "Active",
      "der_participation": "Yes",
      "established_year": 1980
    },
    "version_count": "1.0.0"
  },
  {
    "authorization": "registryauth:cord:X8JY6GM9eY9qbsXmT27ARZXhf2Hkj31UjLjStf4AFVWNsvNhn",
    "recordName": "Utility company 1 - ELC006",
    "description": "Utility company data",
    "details": {
      "company_id": "ELC006",
      "company_name": "Andhra Pradesh Power Utilities",
      "state_region": "Andhra Pradesh",
      "headquarters": "Amaravati",
      "contact_email": "help@appower.in",
      "contact_phone": "0863-45678901",
      "customer_service_portal_url": "https://www.appower.in",
      "status": "Active",
      "der_participation": "No",
      "established_year": 1978
    },
    "version_count": "1.0.0"
  },
  {
    "authorization": "registryauth:cord:X8JY6GM9eY9qbsXmT27ARZXhf2Hkj31UjLjStf4AFVWNsvNhn",
    "recordName": "Utility company 1 - ELC007",
    "description": "Utility company data",
    "details": {
      "company_id": "ELC007",
      "company_name": "Rajasthan Energy Services Ltd",
      "state_region": "Rajasthan",
      "headquarters": "Jaipur",
      "contact_email": "service@rajenergy.com",
      "contact_phone": "0141-76543210",
      "customer_service_portal_url": "https://www.rajenergy.com",
      "status": "Active",
      "der_participation": "Yes",
      "established_year": 1990
    },
    "version_count": "1.0.0"
  },
  {
    "authorization": "registryauth:cord:X8JY6GM9eY9qbsXmT27ARZXhf2Hkj31UjLjStf4AFVWNsvNhn",
    "recordName": "Utility company 1 - ELC008",
    "description": "Utility company data",
    "details": {
      "company_id": "ELC008",
      "company_name": "Kerala State Electricity Board",
      "state_region": "Kerala",
      "headquarters": "Thiruvananthapuram",
      "contact_email": "contact@kseb.in",
      "contact_phone": "0471-65432109",
      "customer_service_portal_url": "https://www.kseb.in",
      "status": "Active",
      "der_participation": "No",
      "established_year": 1957
    },
    "version_count": "1.0.0"
  },
  {
    "authorization": "registryauth:cord:X8JY6GM9eY9qbsXmT27ARZXhf2Hkj31UjLjStf4AFVWNsvNhn",
    "recordName": "Utility company 1 - ELC009",
    "description": "Utility company data",
    "details": {
      "company_id": "ELC009",
      "company_name": "Punjab State Power Corporation Ltd",
      "state_region": "Punjab",
      "headquarters": "Patiala",
      "contact_email": "support@pspcl.in",
      "contact_phone": "0175-34567890",
      "customer_service_portal_url": "https://www.pspcl.in",
      "status": "Active",
      "der_participation": "Yes",
      "established_year": 1968
    },
    "version_count": "1.0.0"
  },
  {
    "authorization": "registryauth:cord:X8JY6GM9eY9qbsXmT27ARZXhf2Hkj31UjLjStf4AFVWNsvNhn",
    "recordName": "Utility company 1 - ELC010",
    "description": "Utility company data",
    "details": {
      "company_id": "ELC010",
      "company_name": "Haryana Vidyut Prasaran Nigam Ltd",
      "state_region": "Haryana",
      "headquarters": "Panchkula",
      "contact_email": "info@hvpnl.gov.in",
      "contact_phone": "0172-98765432",
      "customer_service_portal_url": "https://www.hvpnl.gov.in",
      "status": "Active",
      "der_participation": "No",
      "established_year": 1998
    },
    "version_count": "1.0.0"
  },
  {
    "authorization": "registryauth:cord:X8JY6GM9eY9qbsXmT27ARZXhf2Hkj31UjLjStf4AFVWNsvNhn",
    "recordName": "Utility company 1 - ELC011",
    "description": "Utility company data",
    "details": {
      "company_id": "ELC011",
      "company_name": "Karnataka Power Transmission Corp",
      "state_region": "Karnataka",
      "headquarters": "Bengaluru",
      "contact_email": "support@kptcl.com",
      "contact_phone": "080-87654321",
      "customer_service_portal_url": "https://www.kptcl.com",
      "status": "Active",
      "der_participation": "Yes",
      "established_year": 1975
    },
    "version_count": "1.0.0"
  },
  {
    "authorization": "registryauth:cord:X8JY6GM9eY9qbsXmT27ARZXhf2Hkj31UjLjStf4AFVWNsvNhn",
    "recordName": "Utility company 1 - ELC012",
    "description": "Utility company data",
    "details": {
      "company_id": "ELC012",
      "company_name": "Madhya Pradesh Electricity Corp",
      "state_region": "Madhya Pradesh",
      "headquarters": "Bhopal",
      "contact_email": "support@mpelectricity.com",
      "contact_phone": "0755-23456789",
      "customer_service_portal_url": "https://www.mpelectricity.com",
      "status": "Active",
      "der_participation": "Yes",
      "established_year": 1972
    },
    "version_count": "1.0.0"
  },
  {
    "authorization": "registryauth:cord:X8JY6GM9eY9qbsXmT27ARZXhf2Hkj31UjLjStf4AFVWNsvNhn",
    "recordName": "Utility company 1 - ELC013",
    "description": "Utility company data",
    "details": {
      "company_id": "ELC013",
      "company_name": "Uttar Pradesh Power Corp. Ltd",
      "state_region": "Uttar Pradesh",
      "headquarters": "Lucknow",
      "contact_email": "service@uppcl.in",
      "contact_phone": "0522-12345678",
      "customer_service_portal_url": "https://www.uppcl.in",
      "status": "Active",
      "der_participation": "Yes",
      "established_year": 1988
    },
    "version_count": "1.0.0"
  },
  {
    "authorization": "registryauth:cord:X8JY6GM9eY9qbsXmT27ARZXhf2Hkj31UjLjStf4AFVWNsvNhn",
    "recordName": "Utility company 1 - ELC014",
    "description": "Utility company data",
    "details": {
      "company_id": "ELC014",
      "company_name": "Himachal Pradesh State Power Corp",
      "state_region": "Himachal Pradesh",
      "headquarters": "Shimla",
      "contact_email": "help@hppower.in",
      "contact_phone": "0177-34567890",
      "customer_service_portal_url": "https://www.hppower.in",
      "status": "Active",
      "der_participation": "No",
      "established_year": 1993
    },
    "version_count": "1.0.0"
  },
  {
    "authorization": "registryauth:cord:X8JY6GM9eY9qbsXmT27ARZXhf2Hkj31UjLjStf4AFVWNsvNhn",
    "recordName": "Utility company 1 - ELC015",
    "description": "Utility company data",
    "details": {
      "company_id": "ELC015",
      "company_name": "Jharkhand Bijli Vitran Nigam",
      "state_region": "Jharkhand",
      "headquarters": "Ranchi",
      "contact_email": "info@jbvnl.com",
      "contact_phone": "0651-23456789",
      "customer_service_portal_url": "https://www.jbvnl.com",
      "status": "Active",
      "der_participation": "No",
      "established_year": 2004
    },
    "version_count": "1.0.0"
  },
  {
    "authorization": "registryauth:cord:X8JY6GM9eY9qbsXmT27ARZXhf2Hkj31UjLjStf4AFVWNsvNhn",
    "recordName": "Utility company 1 - ELC016",
    "description": "Utility company data",
    "details": {
      "company_id": "ELC016",
      "company_name": "Bihar State Power Holding Company",
      "state_region": "Bihar",
      "headquarters": "Patna",
      "contact_email": "support@bsphcl.in",
      "contact_phone": "0612-87654321",
      "customer_service_portal_url": "https://www.bsphcl.in",
      "status": "Active",
      "der_participation": "Yes",
      "established_year": 2012
    },
    "version_count": "1.0.0"
  },
  {
    "authorization": "registryauth:cord:X8JY6GM9eY9qbsXmT27ARZXhf2Hkj31UjLjStf4AFVWNsvNhn",
    "recordName": "Utility company 1 - ELC017",
    "description": "Utility company data",
    "details": {
      "company_id": "ELC017",
      "company_name": "Assam Power Distribution Company",
      "state_region": "Assam",
      "headquarters": "Guwahati",
      "contact_email": "info@apdcl.com",
      "contact_phone": "0361-76543210",
      "customer_service_portal_url": "https://www.apdcl.com",
      "status": "Active",
      "der_participation": "Yes",
      "established_year": 2009
    },
    "version_count": "1.0.0"
  },
  {
    "authorization": "registryauth:cord:X8JY6GM9eY9qbsXmT27ARZXhf2Hkj31UjLjStf4AFVWNsvNhn",
    "recordName": "Utility company 1 - ELC018",
    "description": "Utility company data",
    "details": {
      "company_id": "ELC018",
      "company_name": "Chhattisgarh Power Distribution Co",
      "state_region": "Chhattisgarh",
      "headquarters": "Raipur",
      "contact_email": "support@cspdcl.co.in",
      "contact_phone": "0771-98765432",
      "customer_service_portal_url": "https://www.cspdcl.co.in",
      "status": "Active",
      "der_participation": "Yes",
      "established_year": 2001
    },
    "version_count": "1.0.0"
  },
  {
    "authorization": "registryauth:cord:X8JY6GM9eY9qbsXmT27ARZXhf2Hkj31UjLjStf4AFVWNsvNhn",
    "recordName": "Utility company 1 - ELC019",
    "description": "Utility company data",
    "details": {
      "company_id": "ELC019",
      "company_name": "Odisha Power Transmission Corp.",
      "state_region": "Odisha",
      "headquarters": "Bhubaneswar",
      "contact_email": "service@optcl.co.in",
      "contact_phone": "0674-23456789",
      "customer_service_portal_url": "https://www.optcl.co.in",
      "status": "Active",
      "der_participation": "Yes",
      "established_year": 1995
    },
    "version_count": "1.0.0"
  },
  {
    "authorization": "registryauth:cord:X8JY6GM9eY9qbsXmT27ARZXhf2Hkj31UjLjStf4AFVWNsvNhn",
    "recordName": "Utility company 1 - ELC020",
    "description": "Utility company data",
    "details": {
      "company_id": "ELC020",
      "company_name": "Telangana State Power Utility",
      "state_region": "Telangana",
      "headquarters": "Hyderabad",
      "contact_email": "support@tspower.co.in",
      "contact_phone": "040-87654321",
      "customer_service_portal_url": "https://www.tspower.co.in",
      "status": "Active",
      "der_participation": "Yes",
      "established_year": 2015
    },
    "version_count": "1.0.0"
  }
]
