### ISSUE TITLE
UAI WinRoom: Debugging and Setup Activities

### ISSUE THREAD

**Issue by viraj89** [beckn/beckn-utilities#234]
## Description
Perform necessary debugging and setup activities for the UAI WinRoom. Tasks include resolving deployment issues, setting up and registering on the new registry, fixing configuration and response issues, and ensuring smooth functionality as part of the WinRoom activities.

## Goals
- [x] Debug and resolve bap-client deployment issues.
- [x] Create and set up a new registry for the UAI team and register their NP.
- [x] Fix empty response issues in the deployment.
- [x] Resolve configuration issues in `default.yml` for affected users.
- [x] Exclude local setup debugging as it is not supported.

## Expected Outcome
- Deployment issues are resolved, and UAI WinRoom functionalities are fully operational.
- New registry is set up and functional with NP registration completed.
- Configuration and response issues are fixed and verified.

## Acceptance Criteria
- [x] Bap-client deployment issues are resolved.
- [x] New registry is functional, and NP is successfully registered.
- [x] Configuration and response issues are fixed.
- [x] Local setup debugging is confirmed as excluded.

## Mockups / Wireframes
NA

## Product Name
Beckn

## Domain
Open Agri Network 

## Tech Skills Needed
- Deployment Debugging
- Registry Setup
- Configuration Management
- Issue Resolution

## Complexity
Medium

## Category
WinRoom Activities

## Sub Category
UAI Debugging and Setup

**Comment by prasad-takale-eminds** [comment]
- Connected with the team to debug the bap-client deployment
- Created new registry for UAI team and registered their NP on new registry.
- Fixed empty repose issue
- Fixed the `default.yml` issue for some off the user
- Debug local deployment but we dropped this as Faiz mentioned that we are not supporting local setup issue.
