### ISSUE TITLE
Strapi BPP - Staging environment setup

### ISSUE THREAD

**Issue by vishi24** [beckn/beckn-utilities#24]
## Description
The strapi BPP server (https://github.com/beckn/beckn-strapi-bpp) , currently does not have a staging environment, it will be used by the testing team to test the new feature/enhancement done by the development team after testing on the development environment.

## Goals

- [ ] Create a Staging environment for the strapi BPP server.

## Expected Outcome
Staging environment setup with the minimum resources so that it can be used by the testing team to test new features/enhancements.

## Acceptance Criteria

- [ ] The staging environment is up and running for strapi BPP server.

## Implementation Details

NA

## Mockups / Wireframes

NA

---

[Please note that the below section of the ticket ****has to be in the format as mentioned as it is key to enabling proper listing of the project.**** Please only choose the options mentioned under the headings wherever applicable.]

### Product Name

NA

### Project Name

NA

### Organization Name:

FIDE

### Domain

NA

### Tech Skills Needed:

Git
AWS

### Complexity

Medium

### Category

Deployment

### Sub Category

Deployment

**Comment by prasad-takale-eminds** [comment]
We have created a staging environment. 
URL: https://strapi-bpp-stage.becknprotocol.io
