### ISSUE TITLE
Generic Client Repository - Staging environment setup

### ISSUE THREAD

**Issue by vishi24** [beckn/beckn-utilities#25]
## Description
The generic client (https://github.com/beckn/generic-client-layer) , currently does not have a staging environment, it will be used by the testing team to do testing of newly developed features with the existing functionalities to make sure no previous functionality is broken.

## Goals

- [ ] Create a Staging environment for the generic client layer.

## Expected Outcome
Staging environment setup with the minimum resources so that it can be used by the testing team to test any development done by the development team and already gone through developer testing.

## Acceptance Criteria

- [ ] The staging environment is up and running for the generic client layer.

## Implementation Details

NA

## Mockups / Wireframes

NA

---

[Please note that the below section of the ticket ****has to be in the format as mentioned as it is key to enabling proper listing of the project.**** Please only choose the options mentioned under the headings wherever applicable.]

### Product Name

NA

### Project Name

NA

### Organization Name:

FIDE

### Domain

NA

### Tech Skills Needed:

Git
AWS

### Complexity

Medium

### Category

Deployment

### Sub Category

Deployment

**Comment by prasad-takale-eminds** [comment]
We have created the Staging Environment for Generic Client Layer.
URL: https://generic-client-layer-stage.becknprotocol.io/

**Comment by vishi24** [comment]
Is the deployment tested ? Please attach postman screenshot.
