### ISSUE TITLE
Setup Subdomain and Update DNS Records for UKI Microsite

### ISSUE THREAD

**Issue by viraj89** [beckn/beckn-utilities#257]
## Description
The UKI microsite is ready to be moved to the live environment. The task involves setting up a subdomain `uki.becknprotocol.io` and updating the A record in the DNS settings under `becknprotocol.io`.

## Goals
- [x] Create a subdomain `uki.becknprotocol.io`.
- [x] Update the A record in DNS settings with the specified IP.

## Expected Outcome
A functional subdomain `uki.becknprotocol.io` pointing to the specified IP, allowing the UKI microsite to be accessed in the live environment.

## Acceptance Criteria
- [x] Subdomain `uki.becknprotocol.io` is created.
- [x] A record with IP `52.66.179.176` is updated under `becknprotocol.io`.
- [x] Verified that `uki.becknprotocol.io` resolves to the correct IP.

## Mockups / Wireframes
NA

## Product Name
Beckn

## Domain
Agri

## Tech Skills Needed
- DNS management
- Domain and subdomain configuration
- Verification of DNS updates

## Complexity
Low

## Category
DevOps

## Sub Category
DNS Configuration

**Comment by prasad-takale-eminds** [comment]
A DNS entry has been created for `uki.becknprotocol.io` with the following details:

- **Type**: A
- **IP Address**: 52.66.179.176
- **Name**: uki
- **Subdomain**: uki.becknprotocol.io

![Image](https://github.com/user-attachments/assets/f1547408-21a9-41aa-a305-929050f11e82)
