### ISSUE TITLE
ONIX Architecture for user input and individual components

### ISSUE THREAD

**Issue by vishi24** [beckn/beckn-utilities#26]
## Description

The current ONIX installer allows only installation of all components with default configurations, user can not select specific components for installation. Create architecture for ONIX for the below scenarios

1. Accepting user input
2. Deployment of selected components, that will also require user input.

## Goals

- [ ] Create design architecture when user input is taken for the ONIX installer.
- [ ] Create design architecture for ONIX installer in case selected components are installed.

## Expected Outcome

Create the design architecture for user input processing and installation of specific components from the ONIX installer. The design architecture must clearly explain the steps involved in processing and the files that will be affected.

## Acceptance Criteria

- [ ] Document defining the execution flow if user input is accepted for the installation.
- [ ] Document should define the flow in case selected components are installed.

## Implementation Details

NA
## Mockups / Wireframes

NA

---

### Product Name

Beckn
### Project Name

ONIX

### Organization Name:

FIDE

### Domain

NA

### Tech Skills Needed:

Shell scripting

### Complexity

Medium

### Category
Architecture

### Sub Category

Shell script

**Comment by vbabuEM** [comment]
Meeting minutes of the ONIX individual installation demonstration
cc @prasad.takale @Vishwajeet Pratap Singh @faiz mohammed 
1. Add an option to install BAP with Beckn BAP Adapter(Generic client layer)
2. At the beginning of the script, mention that he has two option:
  a. Install all options
  b. Install only some components of the system (Please use the wordings that you already have or get approved from Vishwa)
Only then ask his input. What Faiz mentioned was that if we only show "Do you want to install all components" he might not know what his options are.
3. When user chooses individual option, Faiz mentioned that we should first tell him what all we will ask during installation(primarily related to registration) and show him a document link he can use to go and register at the registry.
4. We should ask for domain name during installation.
5. Do not have automatic registration with registry when installing individual components.
6. Please check all installation scripts and make sure we do not have any cloud credentials inadvertently exposed.
7. Please add support to do all-in-one installation on Windows and Mac
8. After all your work is done, please cleanup the installation folder.
9. After installation the instructions should have the following:
a. How to install the new public key in the registry
b. Details on setting up local tunnel
