### ISSUE TITLE
created a new t2.medium instance for testing beckn-onix using branch beckn-onix-v0.5 features/improvements and did DNS & Nginx configuration for testing it using Postman

### ISSUE THREAD

**Issue by emmayank** [beckn/beckn-utilities#262]
## Description
Created a new `t2.medium` instance to test features and improvements in the `beckn-onix-v0.5` branch. Configured DNS and Nginx to enable testing the instance using Postman.

## Goals
- [x] Deploy Beckn-Onix `v0.5` branch on the `t2.medium` instance.
- [x] Configure DNS to point to the new instance.
- [x] Set up and validate Nginx for proper routing.
- [x] Test API endpoints using Postman for functional validation.

## Expected Outcome
A fully functional testing environment for Beckn-Onix `v0.5` with DNS and Nginx configured, ready for Postman testing.

## Acceptance Criteria
- [x] Beckn-Onix `v0.5` branch is deployed successfully on the `t2.medium` instance.
- [x] DNS configuration allows access to the instance.
- [x] Nginx is set up and routing requests correctly.
- [x] API endpoints are validated using Postman without issues.

## Mockups / Wireframes
NA

## Product Name
Beckn

## Domain
TBD

## Tech Skills Needed
AWS EC2, DNS Configuration, Nginx, Postman Testing

## Complexity
Medium

## Category
Deployment

## Sub Category
Testing Environment

**Comment by em-tpt-bbandi** [comment]
created a new t2.medium instance for testing beckn-onix using branch beckn-onix-v0.5 features/improvements and did DNS & Nginx configuration for testing it using Postman.

the instance is shutdown after the test.

**Comment by prasad-takale-eminds** [comment]
Testing is done refere [#329](https://github.com/beckn/beckn-onix/issues/329)
