### ISSUE TITLE
List user input for ONIX installer

### ISSUE THREAD

**Issue by vishi24** [beckn/beckn-utilities#27]
## Description
The current ONIX installer does not accept any user input, the ONIX installer needs an update to accept user input so that services can be deployed with user-provided custom values.

## Goals

- [ ] Create a list of components for ONIX.
- [ ] Under each component mention what user input can be accepted.

## Expected Outcome
List of ONIX components, under each component list of maximum possible inputs that can be accepted from the user.

## Acceptance Criteria

- [ ] Document having a list of all the ONIX components and their respective maximum possible user inputs.

## Implementation Details

NA

## Mockups / Wireframes

NA

---

[Please note that the below section of the ticket ****has to be in the format as mentioned as it is key to enabling proper listing of the project.**** Please only choose the options mentioned under the headings wherever applicable.]

### Product Name

NA

### Project Name

NA

### Organization Name:

FIDE

### Domain

NA

### Tech Skills Needed:

NA
### Complexity

Medium

### Category

Deployment

### Sub Category

Documentation

**Comment by prasad-takale-eminds** [comment]
Users can input the below details.
Subscriber ID
Subscriber URL
Registry URL
Webhook URL (For BPP)

If the user wants to change the default values of MongoDB, RabbitMQ, and Redis Service the user can change it in **variables.sh** file.

**Comment by vishi24** [comment]
User inputs listed, hence closing the ticket.

Users can input the below details.
Subscriber ID
Subscriber URL
Registry URL
Webhook URL (For BPP)

If the user wants to change the default values of MongoDB, RabbitMQ, and Redis Service the user can change it in variables.sh file.
