### ISSUE TITLE
CI/CD setup - Strapi BPP Development 

### ISSUE THREAD

**Issue by vishi24** [beckn/beckn-utilities#28]
## Description
There is no CI/CD setup for the Strapi BPP (https://github.com/beckn/beckn-strapi-bpp) development environment. Create a CI/CD for the Strapi BPP Develop branch to the Strapi BPP development environment. When the developer pushes the code, it should be deployed on the development environment.

## Goals

- [ ] Working CI/CD for the Strapi BPP development branch to the Strapi BPP development environment.

## Expected Outcome
Working CI/CD pipeline for Strapi BPP develop branch.
When the code is pushed to the development branch, it should be deployed to the development environment.

## Acceptance Criteria

- [ ] Working CI/CD pipeline for Strapi BPP developed branch.

## Implementation Details

NA

## Mockups / Wireframes

NA

---

[Please note that the below section of the ticket **** has to be in the format as mentioned as it is key to enabling proper listing of the project.**** Please only choose the options mentioned under the headings wherever applicable.]

### Product Name

NA

### Project Name

NA

### Organization Name:

FIDE

### Domain

NA

### Tech Skills Needed:

DevOps - Jenkins
### Complexity

Medium

### Category

Deployment

### Sub Category

CI/CD

**Comment by prasad-takale-eminds** [comment]
We have created the CICD pipeline for this. 
URL: https://jenkins.becknprotocol.io/job/strapi/job/strapi-bpp-dev/
