### ISSUE TITLE
CI/CD setup - Strapi BAP development environment

### ISSUE THREAD

**Issue by vishi24** [beckn/beckn-utilities#32]
## Description
There is no CI/CD setup for the Strapi BAP (https://github.com/beckn/beckn-bap-user-strapi) development environment. Create a CI/CD for the Strapi BAP Develop branch to the Strapi BAP development environment. When the developer pushes the code, it should be deployed on the development environment.

## Goals

- [ ] Working CI/CD for the Strapi BAP development branch to the Strapi BAP development environment.

## Expected Outcome
Working CI/CD pipeline for Strapi BAP develop branch.
When the code is pushed to the development branch, it should be deployed to the development environment.

## Acceptance Criteria

- [ ] Working CI/CD pipeline for Strapi BAP developed branch.

## Implementation Details

NA

## Mockups / Wireframes

NA

---

[Please note that the below section of the ticket **** has to be in the format as mentioned as it is key to enabling proper listing of the project.**** Please only choose the options mentioned under the headings wherever applicable.]

### Product Name

NA

### Project Name

NA

### Organization Name:

FIDE

### Domain

NA

### Tech Skills Needed:

DevOps - Jenkins
### Complexity

Medium

### Category

Deployment

### Sub Category

CI/CD

**Comment by prasad-takale-eminds** [comment]
We have created the CICD pipeline for this.
URL: https://jenkins.becknprotocol.io/job/strapi/job/strapi-bap-dev/
