### ISSUE TITLE
CI/CD setup - Strapi BAP staging

### ISSUE THREAD

**Issue by vishi24** [beckn/beckn-utilities#33]
## Description
There is no CI/CD setup for the Strapi BAP (https://github.com/beckn/beckn-bap-user-strapi) staging environment. Create a CI/CD for the Strapi BAP staging branch to the Strapi BAP staging environment. When the PR is merged from develop branch to staging branch it should be deployed on the staging environment.

## Goals

- [ ] Working CI/CD for the Strapi BAP staging branch to the Strapi BAP staging environment.

## Expected Outcome
Working CI/CD pipeline for Strapi BAP staging branch.
When the code is pushed to the staging branch, it should be deployed to the staging environment.

## Acceptance Criteria

- [ ] Working CI/CD pipeline for Strapi BAP staging branch.

## Implementation Details

NA

## Mockups / Wireframes

NA

---

[Please note that the below section of the ticket **** has to be in the format as mentioned as it is key to enabling proper listing of the project.**** Please only choose the options mentioned under the headings wherever applicable.]

### Product Name

NA

### Project Name

NA

### Organization Name:

FIDE

### Domain

NA

### Tech Skills Needed:

DevOps - Jenkins
### Complexity

Medium

### Category

Deployment

### Sub Category

CI/CD

**Comment by prasad-takale-eminds** [comment]
We have created the CICD pipeline for this. 
URL: https://jenkins.becknprotocol.io/job/strapi/job/strapi-bap-stage/
