### ISSUE TITLE
Industry 4.0 Machine Simulator

### ISSUE THREAD

**Issue by vishi24** [beckn/beckn-utilities#34]
## Description
Since live machine endpoints are not available and the code developed by students is not up to the mark, we will create an application that will simulate machine behavior. The application will consist of two end points confirm and status.

## Goals

- [x] Create an application with two endpoints confirm and status.
- [x] Confirm endpoint should accept the configurations required by the machine to process the order.
- [x] Status endpoint will be used to provide the latest status of the order with the machine.

## Expected Outcome
Application with two APIs that can accept orders and provide the latest status of an order.

## Acceptance Criteria

- [ ] Application with two end points that accepts order and give status of order.

## Implementation Details

https://fide-official.atlassian.net/wiki/spaces/BBB/pages/230588433/Industry+4.0+machine+simulator

## Mockups / Wireframes

NA

---

[Please note that the below section of the ticket **** has to be in the format as mentioned as it is key to enabling proper listing of the project.**** Please only choose the options mentioned under the headings wherever applicable.]

### Product Name

NA

### Project Name

NA

### Organization Name:

FIDE

### Domain

NA

### Tech Skills Needed:

Nodejs
MongoDB

### Complexity

Medium

### Category

Development

### Sub Category

REST API

**Comment by shreyvishal** [comment]
Current Status: Both APIs confirm and status are developed on local and pushed to the branch and now the deployment of this application is going on. Once deployed will test it with Sandbox and Strapi

**Comment by shreyvishal** [comment]
Current Status: Simulator APP is ready, deployed and integrated with Sandbox provided endpoints to zoya to integrate it to strapi.
@vishi24
