### ISSUE TITLE
ONIX - Add generic client layer

### ISSUE THREAD

**Issue by vishi24** [beckn/beckn-utilities#41]
## Description

The current ONIX script does not include generic client layer, generic client layer is also required to be added to the ONIX script.

## Goals

- [ ] Create  generic client layer docker image with tag as latest.
- [ ] Push the docker image to the dockerhub.
- [ ] Add generic client layer in the ONIX script as one of the component.
- [ ] Update the variable/config section to include generic client layer.

## Expected Outcome

ONIX script should list generic client layer as one of the component.
When complete stack is deployed generic client layer should also be deployed.

## Acceptance Criteria

- [ ] ONIX layer should be able to install generic client layer if selected/ part of the complete stack.

## Implementation Details

NA

## Mockups / Wireframes
NA

---

[Please note that the below section of the ticket ****has to be in the format as mentioned as it is key to enabling proper listing of the project.**** Please only choose the options mentioned under the headings wherever applicable.]

### Product Name

ONIX
### Project Name

Beckn Utilities
### Tech Skills Needed:

Scripting 
Docker
### Complexity

Medium

### Category

Deployment

### Sub Category

Deployment.

**Comment by prasad-takale-eminds** [comment]
We have added the generic client layer installation. 
PFA the screenshots for the same. 


![Image](https://github.com/beckn/beckn-utilities/assets/84436945/de8f9ebf-0909-4c24-8b81-dce1bdf2c51f)

**Comment by vbabuEM** [comment]
The above two comments were due to a wrong link.
