### ISSUE TITLE
ONIX Create ReadMe/Instructions file

### ISSUE THREAD

**Issue by vishi24** [beckn/beckn-utilities#42]
## Description

ONIX installation needs to have read me / instructions file that will serve to user to understand the different components and redirection links for further details which are already there.

## Goals

- [ ] Readme file should provide the intent of the ONIX and the different ways it can be used. Various options are available and how they will affect the installation and setup.
- [ ] Readme should mention the prerequisites for different options.
- [ ] Readme file should include details about the components of ONIX.
- [ ] Readme should provide link for participant registration on Beckn registry.

## Expected Outcome

The readme file can be used as the documentation for ONIX.

## Acceptance Criteria

- [ ] Readme file with all the above-mentioned details.

## Implementation Details

NA

## Mockups / Wireframes

NA

---

[Please note that the below section of the ticket ****has to be in the format as mentioned as it is key to enabling proper listing of the project.**** Please only choose the options mentioned under the headings wherever applicable.]

### Product Name

ONIX

### Project Name

Beckn utilities

### Tech Skills Needed:

ONIX script
Documentation

### Complexity

Low

### Category

Documentation

### Sub Category

Documentation

**Comment by vishi24** [comment]
@vbabuEM When can we expect the closure ?

**Comment by vbabuEM** [comment]
@vishi24 , isnt this the one that you wrote instead of me? I think we can close this.

**Comment by vbabuEM** [comment]
It is available here https://github.com/beckn/beckn-onix/blob/main/docs/user_guide.md
