### ISSUE TITLE
ONIX - fork registry and gateway repository into beckn repository

### ISSUE THREAD

**Issue by vishi24** [beckn/beckn-utilities#67]
## Description

Registry and Gateway are not part of beckn repository, the source code that is being deployed on all the instances needs to be placed in the beckn repository.
Please create fork of the required repositories in the beckn repository.

## Goals

- [ ] Registry source code in beckn repository
- [ ] Gateway source code in beckn repository

## Expected Outcome

Registry and Gateway repositories forked in the beckn repository.

## Acceptance Criteria

Registry and Gateway repositories forked in the beckn registry.

## Implementation Details

NA

## Mockups / Wireframes

NA

---

NA

### Product Name

NA

### Project Name

NA

### Tech Skills Needed:

Git

### Complexity

Low

**Comment by vishi24** [comment]
@prasad-takale-eminds , please update the ticket with the repository links from where you have forked and the one you have created.

**Comment by prasad-takale-eminds** [comment]
We have created the new repo for Registry App and Gateway App. 
Below are the URL's

Registry URL: https://github.com/beckn/beckn-registry-app
Gateway URL: https://github.com/beckn/beckn-gateway-app
