### ISSUE TITLE
Move ONIX to a separate project

### ISSUE THREAD

**Issue by ravi-prakash-v** [beckn/beckn-utilities#76]
## Description

ONIX is a separate project. It's value prop is much more than a mere utility. Let us not diminish its value by putting it in some obscure folder inside a utilities repo. 

## Goals

- Create a separate repo for onix and move all the code and documentation there
- Readme needs to copied and updated in the new repo with the releases.

onix repo
https://github.com/beckn/onix/tree/develop

**Comment by vbabuEM** [comment]
The latest code from beckn-utilities/onix has been moved to onix git repository.
