### ISSUE TITLE
BAP search provider architecture

### ISSUE THREAD

**Issue by vishi24** [beckn/beckn-utilities#77]
## Description

On the BAP side the search request directly goes to the gateway to search for the products there is no caching mechanism on the BAP side that can be used for searching the products first on the BAP side than on select call actual call to the BPP should be made to fetch further details.
The architecture for the search provider application must clearly state
1. **Process Flow for Search Request**: Upon the introduction of the search provider, the search request will follow a defined process flow. This flow should be clearly outlined, detailing how the request is received, processed, and responded to by the search provider.

2. **Caching Mechanism**: The search provider will employ a caching mechanism to optimize search performance. This mechanism should be specified, outlining how and where caching occurs within the architecture.

3. **Frequency of Updates**: The frequency at which the search provider updates its data should be established. This ensures that search results remain accurate and up-to-date.

4. **Continuous Feed Loop**: A continuous feed loop from the select call to the search provider database needs to be established. This loop ensures that relevant data is constantly fed into the search provider, enabling timely updates and accurate search results.

5. **Integration of Caching**: Clarify whether caching will be integrated into the search provider's startup process or if it will be dynamically populated at runtime. This distinction ensures efficient resource utilization and optimal performance.

6. **Cache Maintenance Mechanism**: Define the mechanism for maintaining the cache's accuracy and relevance. This includes strategies for updating cache entries as new data becomes available and removing outdated entries.

7. **Technologies Used**: Specify the applications and software to be utilized in implementing the search provider. This may include technologies such as Kafka, Redis, or others, depending on the specific requirements and architecture of the system.

## Goals

- [ ] Search provider architecture document that clearly explains the points mentioned above

## Expected Outcome

BAP should be able to search within the search provider without making calls to the gateway, also the data should be up to date with the BPP some lag can be considered.

## Acceptance Criteria

- [ ] Clear and detailed document with all the information and diagrams where possible.

## Implementation Details

NA
## Mockups / Wireframes

[Include links to any visual aids, mockups, wireframes, or diagrams that help illustrate what the final product should look like. This is not always necessary, but can be very helpful in many cases.]

---

[Please note that the below section of the ticket ****has to be in the format as mentioned as it is key to enabling proper listing of the project.**** Please only choose the options mentioned under the headings wherever applicable.]

### Product Name

BAP search provider

### Project Name

BAP search provider

### Tech Skills Needed:

Architecting applicationd\s

### Complexity

High

### Category

Software Architecture

### Sub Category

Software Architecture

**Comment by vbabuEM** [comment]
There are other initiatives related to search provider which have a much larger scope and are being worked on. Closing this issue for now.
