### ISSUE TITLE
Test ONIX script

### ISSUE THREAD

**Issue by vishi24** [beckn/beckn-utilities#82]
## Description

Test the ONIX script by setting up two networks from scratch, these networks will have 6 EC2 instances in total with details as below.

EC2 - Instances Applications | Pre configured Domains
-- | --
BAP protocol server | retail-bap.becknprotocol.io
Gateway and Registry | gateway-retail.becknprotocol.ioregistry-retail.becknprotocol.io
BPP - Protocol server and Strapi | retail-bpp.becknprotocol.io
BAP protocol server | energyy-bap.becknprotocol.io
BPP - Protocol server and Strapi | energy-bpp.becknprotocol.io
Gateway and Registry | gateway-energy.becknprotocol.ioregistry-energy.becknprotocol.io

## Goals

- [ ] Test the ONIX script for any gaps and bugs
- [ ] Setup two networks with the components and domains listed.

## Expected Outcome

Two network with defined details.

## Acceptance Criteria

- [ ] Working networks setup

### Tech Skills Needed:

AWS
ONIX

### Complexity

Low

### Category

Deployment

### Sub Category

Deployment

**Comment by vbabuEM** [comment]
It is now available end to end. The only thing missing is the new Strapi BPP. I will paste a link to the user guide and video once done.

**Comment by vbabuEM** [comment]
The two networks requested were setup. During setup, multiple issues were noticed and have been raised in the ONIX github issue list.
