### ISSUE TITLE
Relookup API for AI chatbot

### ISSUE THREAD

**Issue by vishi24** [beckn/beckn-utilities#83]
Add a server with a look  endpoint that gives back BAP list in the following format. This will be used temorarily to switch networks. 
{
        "url": "http://ec2-13-126-143-70.ap-south-1.compute.amazonaws.com:5001",
        "domains": [
            "energy",
            "EV"
        ],
        "description": "Network with EV charging providers, greeen energy providers"
    }

**Comment by vbabuEM** [comment]
This has been deployed to bap-switch.becknprotocol.io. I am wondering if this is worth committing to a git. Maybe I will do it in some personal repo for the time being. We do not expect this to be useful post the March 20 demo.
