### ISSUE TITLE
Creation of subdomain mapping for energy 

### ISSUE THREAD

**Issue by vbabuEM** [beckn/beckn-utilities#86]
Please create the following subdomains and set them to three elastic ips. This is required for ONIX Demo on March 20.

energy-bap.becknprotocol.io - EIP 1
energy-bpp.becknprotocol.io - EIP 2
gateway-energy.becknprotocol.io - EIP 3
registry-energy.becknprotocol.io - EIP 3
bap-switch.becknprotocol.io - EIP 3 (This should be mapped to port 3145. The lookup server will run there)

**Comment by vbabuEM** [comment]
Please also configure the nginx reverse proxy to point to the right ports for the components

**Comment by prasad-takale-eminds** [comment]
Created below DNS entries. 

IP: ec2-15-207-51-219.ap-south-1.compute.amazonaws.com
DNS
https://energy-bpp.becknprotocol.io/
https://energy-bpp-client.becknprotocol.io


IP: ec2-65-0-185-230.ap-south-1.compute.amazonaws.com
DNS
https://energy-bap.becknprotocol.io
https://energy-bap-client.becknprotocol.io


IP: ec2-13-201-55-21.ap-south-1.compute.amazonaws.com
DNS
https://registry-energy.becknprotocol.io
https://gateway-energy.becknprotocol.io
https://bap-switch.becknprotocol.io
